In [1]:
import numpy as np
steps = np.array([3191, 230, 9193, 4670, 164, 3820, 9093])
print(np.min(steps))
print(np.max(steps))
print(np.sum(steps))
print(round(np.average(steps), 2))

164
9193
30361
4337.29


In [2]:
month_results = np.array([56, 100, 33, 0, 45, 45, 46, 34, 89, 180, 60, 45, 45, 44, 46, 45, 0, 0, 15, 90, 301, 197, 20, 60, 45, 45, 42, 45])
print(month_results.reshape(4,7))

[[ 56 100  33   0  45  45  46]
 [ 34  89 180  60  45  45  44]
 [ 46  45   0   0  15  90 301]
 [197  20  60  45  45  42  45]]


In [3]:
month_results = np.array([56, 100, 33, 0, 45, 45, 46, 34, 89, 180, 60, 45, 45, 44, 46, 45, 0, 0, 15, 90, 301, 197, 20, 60, 45, 45, 42, 45])
print(month_results.shape)

(28,)


In [5]:
import numpy as np 
halley_commet = np.arange(start=1986, stop=3000, step=75)
print(halley_commet)

[1986 2061 2136 2211 2286 2361 2436 2511 2586 2661 2736 2811 2886 2961]


In [17]:
sum = [x for x in range(10)]
print(sum)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [1]:
List1 = [1,2]
List2 = List1
List1[0] = 3 
print(List2)

[3, 2]
