# **Slicing in Python and Numpy**

* sequence[start:stop:step]
- start : where to start slicing (inclusive)
- stop : where to stop slicing (exclusive) `important to note that the stop index is not included in the result`
- step : how many steps to jump while slicing (default is 1)


# **Slicing in Python Strings**

In [2]:

text = "Hello World"
#       0123456789...

# Basic slicing
print(text[0:5])      # "Hello"    → index 0 to 4
print(text[6:11])     # "World"    → index 6 to 10
print(text[0:5:1])    # "Hello"    → step 1 (default)
print(text[0:5:2])    # "Hlo"      → every 2nd character

# Leaving parts empty
print(text[:5])       # "Hello"    → start from beginning
print(text[6:])       # "World"    → go till end
print(text[:])        # "Hello World" → full copy

# Step only
print(text[::2])      # "HloWrd"   → every 2nd char
print(text[::3])      # "HlWl"     → every 3rd char




Hello
World
Hello
Hlo
Hello
World
Hello World
HloWrd
HlWl
lo World


# Negative Indexing in string

In [7]:
text = "Hello World"
#             -5-4-3-2-1
#        -11 ........  -1

print(text[-5:])      # "World"    → last 5 characters
print(text[-5:-2])    # "Wor"      → index -5 to -3
print(text[-1])       # "d"        → last character
print(text[-3:-1])    # "rl"
print(text[:-5])      # "Hello "   → everything except last 5 characters
print(text[-6:-1])    # "Worl"     → from index -6 to -2

# Negative step = REVERSE
print(text[::-1])     # "dlroW olleH"  → reverse string
print(text[::-2])     # "drWolH"       → reverse, every 2nd

# In slicing, x is inclusive and y is exclusive, even with negative indices.

World
Wor
d
rl
Hello 
 Worl
dlroW olleH
dlroW olleH
drWolH


# Slicing in Python Lists

In [8]:
nums = [10, 20, 30, 40, 50, 60, 70]
#        0   1   2   3   4   5   6

# Basic
print(nums[1:4])      # [20, 30, 40]
print(nums[:3])       # [10, 20, 30]
print(nums[4:])       # [50, 60, 70]
print(nums[:])        # [10, 20, 30, 40, 50, 60, 70] → copy

# With step
print(nums[::2])      # [10, 30, 50, 70] → every 2nd
print(nums[1::2])     # [20, 40, 60]     → start at 1, every 2nd
print(nums[1:6:2])    # [20, 40, 60]     → from 1 to 5, every 2nd

# Negative
print(nums[-3:])      # [50, 60, 70]
print(nums[-4:-1])    # [40, 50, 60]
print(nums[::-1])     # [70, 60, 50, 40, 30, 20, 10] → reversed
print(nums[::-2])     # [70, 50, 30, 10]

#Modifying 

nums = [10, 20, 30, 40, 50]

# Replace a section
nums[1:3] = [200, 300]
print(nums)           # [10, 200, 300, 40, 50]

# Delete a section
nums[1:3] = []
print(nums)           # [10, 40, 50]

# Insert without replacing
nums[1:1] = [99, 88]
print(nums)           # [10, 99, 88, 40, 50]

[20, 30, 40]
[10, 20, 30]
[50, 60, 70]
[10, 20, 30, 40, 50, 60, 70]
[10, 30, 50, 70]
[20, 40, 60]
[20, 40, 60]
[50, 60, 70]
[40, 50, 60]
[70, 60, 50, 40, 30, 20, 10]
[70, 50, 30, 10]
[10, 200, 300, 40, 50]
[10, 40, 50]
[10, 99, 88, 40, 50]


# Slicing in tuples 
* tuples are immutable, but we can still slice them to create new tuples.
* same as list slicing but can't modify the original tuple.

In [ ]:
# Same as list but CANNOT modify
t = (1, 2, 3, 4, 5)

print(t[1:4])         # (2, 3, 4)
print(t[::-1])        # (5, 4, 3, 2, 1)
print(t[::2])         # (1, 3, 5)

# t[1:3] = (9, 9)    ← ERROR! tuples are immutable will not work can be modified 

# slicing in numpy arrays

Python list slicing - create a copy of a list
python numpy array slicing - creates a view of the original array (not a copy)
- changes to the view will affect the original array, and vice versa.


In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60, 70])
#                0   1   2   3   4   5   6

# Basic - same as Python lists
print(arr[1:4])       # [20 30 40]
print(arr[:3])        # [10 20 30]
print(arr[4:])        # [50 60 70]
print(arr[::2])       # [10 30 50 70]
print(arr[::-1])      # [70 60 50 40 30 20 10]
print(arr[-3:])       # [50 60 70]

# View vs Copy in Numpy Slicing

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

# This is a VIEW (not a copy)
sliced = arr[1:4]
sliced[0] = 999

print(arr)            # [10 999 30 40 50] ← ORIGINAL CHANGED!
print(sliced)         # [999 30 40]

# To make a real COPY use .copy()
arr = np.array([10, 20, 30, 40, 50])
sliced_copy = arr[1:4].copy()
sliced_copy[0] = 999

print(arr)            # [10 20 30 40 50]  ← original safe
print(sliced_copy)    # [999 30 40]

# 2d array slicing in numpy IMPORTANT


In [ ]:
arr2d = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

# Think of it as [rows, columns]
#                  ↑      ↑


print(arr2d[0])         # [1 2 3 4]        → first row
print(arr2d[1])         # [5 6 7 8]        → second row
print(arr2d[-1])        # [13 14 15 16]    → last row
print(arr2d[0:2])       # first 2 rows
                        # [[1  2  3  4]
                        #  [5  6  7  8]]
print(arr2d[1:3])       # rows 1 and 2
                        # [[5  6  7  8]
                        #  [9 10 11 12]]

# Row slicing

In [ ]:
print(arr2d[0])         # [1 2 3 4]        → first row
print(arr2d[1])         # [5 6 7 8]        → second row
print(arr2d[-1])        # [13 14 15 16]    → last row
print(arr2d[0:2])       # first 2 rows
                        # [[1  2  3  4]
                        #  [5  6  7  8]]
print(arr2d[1:3])       # rows 1 and 2
                        # [[5  6  7  8]
                        #  [9 10 11 12]]

# Column Slicing

In [ ]:
print(arr2d[:, 0])      # [1 5 9 13]       → first column
print(arr2d[:, -1])     # [4 8 12 16]      → last column
print(arr2d[:, 1:3])    # columns 1 and 2
                        # [[ 2  3]
                        #  [ 6  7]
                        #  [10 11]
                        #  [14 15]]

# Row AND Column Together

In [ ]:
# arr2d[row_slice, col_slice]

print(arr2d[0:2, 0:2])  # top-left 2x2 block
                        # [[1 2]
                        #  [5 6]]

print(arr2d[1:3, 1:3])  # middle 2x2 block
                        # [[ 6  7]
                        #  [10 11]]

print(arr2d[0:2, 2:4])  # top-right 2x2 block
                        # [[3 4]
                        #  [7 8]]

print(arr2d[:, 0:2])    # ALL rows, first 2 columns
                        # [[ 1  2]
                        #  [ 5  6]
                        #  [ 9 10]
                        #  [13 14]]

print(arr2d[0:2, :])    # first 2 rows, ALL columns
                        # [[1 2 3 4]
                        #  [5 6 7 8]]

# Step Slicing in 2D arrays

In [ ]:
print(arr2d[::2, ::2])  # every other row AND column
                        # [[ 1  3]
                        #  [ 9 11]]

print(arr2d[::-1, :])   # reverse rows
                        # [[13 14 15 16]
                        #  [ 9 10 11 12]
                        #  [ 5  6  7  8]
                        #  [ 1  2  3  4]]

print(arr2d[:, ::-1])   # reverse columns
                        # [[ 4  3  2  1]
                        #  [ 8  7  6  5]
                        #  [12 11 10  9]
                        #  [16 15 14 13]]

# 3D Array Slicing

In [ ]:
arr3d = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7,  8,  9],
     [10, 11, 12]]
])
# Shape = (2, 2, 3) → 2 blocks, 2 rows, 3 columns
# Think: [block, row, column]

print(arr3d[0])         # first block
                        # [[1 2 3]
                        #  [4 5 6]]

print(arr3d[1])         # second block
                        # [[ 7  8  9]
                        #  [10 11 12]]

print(arr3d[0, 1])      # first block, second row
                        # [4 5 6]

print(arr3d[0, 1, 2])   # first block, second row, third col
                        # 6

print(arr3d[:, 0, :])   # all blocks, first row, all cols
                        # [[1 2 3]
                        #  [7 8 9]]

print(arr3d[:, :, 1])   # all blocks, all rows, col index 1
                        # [[ 2  5]
                        #  [ 8 11]]

# Example 1 Comprehension List

In [1]:
language = "Japanese"
lst = [i for i in language]
print(type(lst))
print(lst)

<class 'list'>
['J', 'a', 'p', 'a', 'n', 'e', 's', 'e']


In [2]:
# Generation numbers 
numbers = [i for i in range(100)]
print(numbers)

squares = [i * i for i in range(10)]
print(squares)

numbers = [(i, i*i) for i in range(11)]
print(numbers)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[(0, 0), (1, 1), (2, 4), (3, 9), (4, 16), (5, 25), (6, 36), (7, 49), (8, 64), (9, 81), (10, 100)]


In [ ]:
even_number = [i for i in range(21) if i % 2 == 0]
print(even_number)

odd_number = [i for i in range(21) if i % 2 != 0]
print(odd_number)

numbers = [-8, -7, -3, -1, 0, 1, 3, 4, 5, 7, 6, 8, 10]
positive_even_number = [i for i in numbers if i % 2 == 0 and i > 0]
print(positive_even_number)

list_of_numbers = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
flattened_list = [number for row in list_of_numbers for number in row]
print(flattened_list)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
[4, 6, 8, 10]
[[-8, -7, -3, -1, 0, 1, 3, 4, 5, 7, 6, 8, 10], [-8, -7, -3, -1, 0, 1, 3, 4, 5, 7, 6, 8, 10], [-8, -7, -3, -1, 0, 1, 3, 4, 5, 7, 6, 8, 10]]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
